### ISSUE TITLE
This ipinfo extension is not working at all. Always getting  ip fetch error

### ISSUE THREAD

**Issue by jeevaoffgamers** [kartik-v/yii2-ipinfo#2]
This ipinfo extension is not working at all. Always getting ip fetch error

**Comment by alexsuter** [comment]
@jeevaoffgamers That's because http://www.hostip.info/ is currently not available.

**Comment by jeevaoffgamers** [comment]
@alexsuter  Alex, OK thanks for your findings. Is there any way to solve this issue?. (by changing service provider, etc). I can fetch country and other information based on IP address using IP2location Yii2 extension. But I am using kartik yii extensions at many places of my project, I would like to follow kartik extensions for uniformity. Hope you understand my thought. Waiting for your reply.

**Comment by kartik-v** [comment]
The extn currently depends on the hostip service provider to be available. I would try to see when I get time to create an alternate functionality without depending on the hostip provide r.

**Comment by jeevaoffgamers** [comment]
@kartik-v  Thanks Kartik for your reply. I would like to thank you and appreciate your consideration on my request.

**Comment by kartik-v** [comment]
Currently check #3 for an interim enhancement to use jQuery ajax asynchronously. However, it still relies on hostip.info to be available.

**Comment by jeevaoffgamers** [comment]
@kartik-v  What about without depending on the hostip provider as you mentioned me earlier?.

**Comment by kartik-v** [comment]
I have changed the plugin to use http://www.freegeoip.net as the api. This will also allow you to run locally if you download it.

You can download this and run from your server (just change the `$api` property of the widget to point to your server downloaded URL).
