### ISSUE TITLE
Getting Mixed Content protocol error when loading from https while the freegeoip loading from http. 

### ISSUE THREAD

**Issue by gajen0981** [kartik-v/yii2-ipinfo#8]
Could we make the request via "//freegeoip.net*"?

`Mixed Content: The page at 'https://example.com' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://freegeoip.net/json/107.77.203.47'. This request has been blocked; the content must be served over HTTPS.
send @ all-015600bac8ac71a8cb7c9e05a05b3501.js:561
all-015600bac8ac71a8cb7c9e05a05b3501.js:561 XMLHttpRequest cannot load http://freegeoip.net/json/107.77.203.47. Failed to start loading.`

**Comment by kartik-v** [comment]
Get the updated code and release v1.0.0 - freegeoip has updated its stack to `apilayer` and needs an api access key. So default `IpConfig::api` property is set to `http://api.ipstack.com/`.

With regards to your issue you can always override the `IpConfig::api` property as per your need.
